Traceback (most recent call last):
  File "/afs/ifh.de/user/s/steinrob/Desktop/python/stacking/RunLocal.py", line 101, in <module>
    k=i, n_trials=n_trials, path=path, seed=seed)
  File "/afs/ifh.de/user/s/steinrob/Desktop/python/stacking/scripts/GenerationControl.py", line 57, in generate_test_statistics
    self.write_result_to_file(path, k, test_stats)
  File "/afs/ifh.de/user/s/steinrob/Desktop/python/stacking/scripts/GenerationControl.py", line 282, in write_result_to_file
    self.check_if_pkl_file_exists(path)
  File "/afs/ifh.de/user/s/steinrob/Desktop/python/stacking/scripts/GenerationControl.py", line 310, in check_if_pkl_file_exists
    pkl_file = open(path, 'wb')
IOError: [Errno 122] Disk quota exceeded: '/afs/ifh.de/user/s/steinrob/Desktop/python/stacking/results/results_test_alignment_scaling_offset_-6.0_0.0__115.789473684_2527292502.pkl'
